
//------------------------------------------------------------------------------
//     This code was generated by template for T4 on ConstDefinition.h
//     Generated at 07/06/2020 15:09:18
//------------------------------------------------------------------------------

namespace Constants
{
    public class ThorRealTimeData
    {
		public const double CELSIUS_TO_KELVIN = 273.15;
		public const int MSG_LENGTH = 256;
		public const int SEC2MSEC = 1000;
		public const int M2UM = 1000000;
		public const double MAX_TASK_WAIT_TIME = 10.0;
		public const double MIN_THREAD_TIME = 0.1;
		public const int CLK_RATE_20MHZ = 20000000;
		public const int MHZ = 1000000;
		public const double PI = 3.1415926535897932384626433832795;
		public const int NYQUIST_RATIO = 2;
		public const double HUNDRED_PERCENT = 100.0;
		public const double MIN_VALUE_LOG = 0.000000000001;
		public const double BOLTZMAN_CONST = 0.0000000000000000000000138064852;
		public const string SETTINGS_FILE_NAME = "ThorRealTimeDataSettings.xml";
		public const string OTM_SETTINGS_FILE = "OTMSettings.xml";
		public const string CROSSTALK = "CROSSTALK";
		public const string POWERSPECTRUMX = "POWERSPECTRUMX";
		public const string POWERSPECTRUMY = "POWERSPECTRUMY";
		public const string LORENTZIANFITX = "LORENTZIANFITX";
		public const string LORENTZIANFITY = "LORENTZIANFITY";
		public const string VAR = "VAR";
 
    }
}