#pragma once

namespace tiff
{
	enum DistanceUnit {
		DISTANCE_UNDEFINED = -1,
		DISTANCE_KILOMETER = 1,
		DISTANCE_METER = 2,
		DISTANCE_MILLIMETER = 3,
		DISTANCE_MICROMETER = 4,
		DISTANCE_NANOMETER = 5,
		DISTANCE_PICOMETER = 6,
	};

	enum Shape {
		SHAPE_UNDEFINED = -1,
		SHAPE_RECTANGLE = 1,
		SHAPE_ELLIPSE = 2,
	};

	enum PixelType {
		PIXEL_UNDEFINED = -1,
		PIXEL_INT8 = 0,
		PIXEL_UINT8 = 1,
		PIXEL_UINT16 = 2,
		PIXEL_INT16 = 3,
		PIXEL_FLOAT32 = 4,
	};

	enum ImageType {
		IMAGE_GRAY = 0,
		IMAGE_RGB = 1
	};

	enum TimeUnit {
		TIME_UNDEFINED = -1,
		TIME_SECOND = 1,
		TIME_MILLISECOND = 2,
		TIME_MICROSECOND = 3,
		TIME_NANOSECOND = 4,
		TIME_PICOSECOND = 5,
		TIME_FEMTOSECOND = 6,
	};

	enum OpenMode {
		CREATE_MODE = 1,
		READ_WRITE_MODE = 2,
		READ_ONLY_MODE = 3,
	};

	enum ErrorCode {
		STATUS_OK = 0,

		TIFF_ERR_USELESS_HDL = -1,
		TIFF_ERR_READ_DATA_FROM_FILE_FAILED = -2,
		TIFF_ERR_OPEN_FILE_PARAMETER_ERROR = -3,
		TIFF_ERR_OPEN_FILE_FAILED = -4,
		TIFF_ERR_CLOSE_FILE_FAILED = -5,
		TIFF_ERR_NO_TIFF_FORMAT = -6,
		TIFF_ERR_BLOCK_SIZE_IN_IFD_IS_EMPTY = -7,
		TIFF_ERR_NEED_IFD_NOT_FOUND = -8,
		TIFF_ERR_BLOCK_OUT_OF_RANGE = -9,
		TIFF_ERR_NO_IFD_FOUND = -10,
		TIFF_ERR_FIRST_IFD_STRUCT_NOT_COMPLETE = -11,
		TIFF_ERR_BLOCK_OFFSET_OUT_OF_RANGE = -12,
		TIFF_ERR_TAG_NOT_FOUND = -13,
		TIFF_ERR_BAD_PARAMETER_VALUE = -14,
		TIFF_ERR_IFD_ALREADY_EXIST = -15,
		TIFF_ERR_IFD_OUT_OF_DIRECTORY = -16,
		TIFF_ERR_IFD_FULL = -17,
		TIFF_ERR_UNSUPPORTED_BITS_PER_SAMPLE = -18,

		ERR_FILE_PATH_ERROR = -101,
		ERR_HANDLE_NOT_EXIST = -102,
		ERR_PLATES_REPEAT_SET = -103,
		ERR_BUFFER_SIZE_ERROR = -104,
		ERR_BUFFER_IS_NULL = -105,
		ERR_PLATES_NOT_EXIST = -106,
		ERR_SCANS_NOT_EXIST = -107,
		ERR_FRAME_NOT_EXIST = -108,
		ERR_DATA_NOT_EXIST = -109,
		ERR_MODIFY_NOT_ALLOW = -110,
		ERR_CREATE_CONTAINER_FAILED = -111,
		ERR_CONTAINER_INVALID = -112,
		ERR_ZIP = -113,
		ERR_CREATE_OME_XML_FAILED = -114,
		ERR_READ_OME_XML_FAILED = -115,
		ERR_XML_TO_PLATES_FAILED = -116,
		ERR_XML_TO_SCAN_FAILED = -117,
		ERR_PLATES_TO_XML_FAILED = -118,
		ERR_SCANS_TO_XML_FAILED = -119,
		ERR_PAREMETER_IS_NULL = -120,
		ERR_NO_CONTAINER_EXIST = -121,
		ERR_GET_IMAGEINFO_FAILED = -122,
		ERR_GET_BLOCK_DATA_FAILED = -123,
		ERR_CREATE_IFD_FAILED = -124,
		ERR_DECOMPRESS_JPEG_FAILED = -125,
		ERR_OPEN_TIFF_FAILED = -126,
		ERR_SET_TAG_FAILED = -127,
		ERR_SAVE_BLOCK_FAILED = -128,
		ERR_CLOSE_FILE_FAILED = -129,
		ERR_SCAN_ID_EXIST = -130,
		ERR_GET_OMEXML_FAILED = -131,
		ERR_ROW_OUT_OF_RANGE = -132,
		ERR_COLUMN_OUT_OF_RANGE = -133,
		ERR_GET_TAG_FAILED = -134,
		ERR_SCALELEVEL_NOT_EXIST = -135,
		ERR_THUMBNAIL_NOT_EXIST = -136,
		ERR_STRIDE_NOT_CORRECT = -137,
		ERR_DATA_TYPE_NOTSUPPORT = -138,
		ERR_COMPRESS_TYPE_NOTSUPPORT = -139,
		ERR_TAG_TYPE_NOTSUPPORT = -140,
		ERR_GET_MIN_VALUE_FAILED = -141,
		ERR_GET_MAX_VALUE_FAILED = -142,
		ERR_COMPRESS_ERROR = -143,
		ERR_DECOMPRESS_LZW_FAILED = -144,
		ERR_DECOMPRESS_LZ4_FAILED = -145,
		ERR_RAWCONTAINER_IS_NOT_EXIST = -146,
		ERR_DECOMPRESS_ZLIB_FAILED = -147,
		ERR_OPENMODE = -148,
		ERR_SAVEDATA_WITHOUT_INFO = -149,
		ERR_TAG_CONDITION_NOT_MET = -150,
		ERR_P2D_SHIFT_FAILED = -151,
		ERR_P2D_COPY_FAILED = -152,
		ERR_P2D_RESIZE_FAILED = -153,
	};

	enum CompressionMode {
		COMPRESSION_NONE = 0,
		COMPRESSION_LZ4 = 1,
		COMPRESSION_LZW = 2,
		COMPRESSION_JPEG = 3,
		COMPRESSION_ZIP = 4,
	};

	struct SingleImageInfo
	{
		unsigned int width;
		unsigned int height;
		unsigned short valid_bits;
		PixelType pixel_type;
		ImageType image_type;
		CompressionMode compress_mode;
	};
}