#// -------------------------------------------------------------------------
#//
#// PRODUCT:			DMA Driver
#// MODULE NAME:		version.inc
#//
#// MODULE DESCRIPTION:
#//
#// Contains the Version number for the Driver .inf file
#//
#// $Revision:  $
#// Oct-2019    DZimmerman    Modified for ThorDAQ (SDK)
#//
#// ------------------------- CONFIDENTIAL ----------------------------------
#//
#//              Copyright (c) 2016 by Northwest Logic, Inc.
#//                       All rights reserved.
#//
#// Trade Secret of Northwest Logic, Inc.  Do not disclose.
#//
#// Use of this source code in any form or means is permitted only
#// with a valid, written license agreement with Northwest Logic, Inc.
#//
#// Licensee shall keep all information contained herein confidential
#// and shall protect same in whole or in part from disclosure and
#// dissemination to all third parties.
#//
#//
#//                        Northwest Logic, Inc.
#//                  1100 NW Compton Drive, Suite 100
#//                      Beaverton, OR 97006, USA
#//
#//                        Ph:  +1 503 533 5800
#//                        Fax: +1 503 533 5900
#//                      E-Mail: info@nwlogic.com
#//                           www.nwlogic.com
#//
#// -------------------------------------------------------------------------

#
#
#
VERSION=6.0.0.0000
