#define VER_MAJOR_NUM               4
#define VER_MINOR_NUM               8
#define VER_SUBMINOR_NUM			2
#define VER_BUILD_NUM               0000

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VER_MAJOR_NUM_STR       STRINGIZE(VER_MAJOR_NUM)
#define VER_MINOR_NUM_STR       STRINGIZE(VER_MINOR_NUM)
#define VER_SUBMINOR_NUM_STR    STRINGIZE(VER_SUBMINOR_NUM)
#define VER_BUILD_NUM_STR       STRINGIZE(VER_BUILD_NUM)

#define VER_PRODUCTVERSION			VER_MAJOR_NUM, VER_MINOR_NUM, VER_SUBMINOR_NUM, VER_BUILD_NUM
#define VER_PRODUCTVERSION_STR		VER_MAJOR_NUM_STR "." VER_MINOR_NUM_STR "." VER_SUBMINOR_NUM_STR "." VER_BUILD_NUM_STR

#define VER_LEGALCOPYRIGHT_YEARS    "2008-2013"
#define VER_PRODUCTNAME_STR         "3rd Party PCI Express Core"
#define VER_INTERNALNAME_STR        "ThorDaqDrv.sys"
#define VER_COMPANYNAME_STR         "Thorlabs, Inc."
#define VER_FILEDESCRIPTION_STR     "PCI Express DMA Reference Driver"
#define VER_LEGALCOPYRIGHT_STR      VER_LEGALCOPYRIGHT_YEARS " " VER_COMPANYNAME_STR